import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: {
    absolute: 'Privacy Policy | Lumii Advisory',
  },
  description:
    'How Lumii Advisory collects, uses and protects your data. Plain-English privacy policy compliant with the Australian Privacy Act.',
  alternates: {
    canonical: 'https://lumiiadvisory.com/privacy-policy',
  },
}

const sections = [
  {
    heading: '1. Who we are',
    body: (
      <>
        Lumii Advisory (&ldquo;Lumii&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo; or &ldquo;us&rdquo;) is a sole-trader
        consulting business operated by Agata Adamczak, based in Sydney, NSW, Australia. This policy explains how we
        handle personal information collected through{' '}
        <Link href="/" className="text-gold hover:text-near-black underline">
          lumiiadvisory.com
        </Link>{' '}
        and through our advisory engagements. We comply with the Australian Privacy Principles (APPs) under the{' '}
        <em>Privacy Act 1988</em> (Cth).
      </>
    ),
  },
  {
    heading: '2. What we collect',
    body: (
      <>
        We only collect information you provide directly or that is generated by your use of the site:
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Name, email, company and message content when you submit our contact or discovery-call form.</li>
          <li>Email address when you opt in to receive an Insights or resource follow-up.</li>
          <li>
            Anonymous traffic and behaviour data via Google Analytics 4 (page views, referrer, approximate location,
            device type). We do not link this data to identifiable individuals.
          </li>
          <li>Standard server logs (IP, user agent) retained for security and debugging purposes only.</li>
        </ul>
      </>
    ),
  },
  {
    heading: '3. How we use your information',
    body: (
      <>
        We use your information solely to:
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Respond to your enquiry and arrange any discovery call or proposal you request.</li>
          <li>Deliver any resource, checklist, or content you specifically request.</li>
          <li>Improve the website&rsquo;s structure, content and performance.</li>
          <li>Comply with legal and tax record-keeping obligations.</li>
        </ul>
        We do not sell, rent or trade your personal information. We do not use it to train any AI model.
      </>
    ),
  },
  {
    heading: '4. Who we share information with',
    body: (
      <>
        We share personal information only with vetted service providers who act on our behalf and only to the extent
        necessary:
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Google Workspace &amp; Gmail — email correspondence and document storage.</li>
          <li>Netlify — website hosting and form submission delivery.</li>
          <li>Google Analytics 4 — anonymous website analytics.</li>
          <li>Calendly — discovery-call scheduling, where used.</li>
        </ul>
        These providers are bound by their own privacy policies and (where applicable) by data-processing agreements.
        We may also disclose information where required by law.
      </>
    ),
  },
  {
    heading: '5. Where your data is stored',
    body: 'Most of our service providers store data in the United States or Europe under standard contractual clauses or equivalent safeguards. By submitting information to us you consent to your data being processed outside Australia for these purposes.',
  },
  {
    heading: '6. How long we keep it',
    body: 'We retain enquiry and engagement-related records for as long as the relationship is active and for up to seven years afterwards to meet Australian tax and record-keeping obligations. Anonymous analytics data is retained on default Google Analytics 4 settings (currently 14 months).',
  },
  {
    heading: '7. Your rights',
    body: (
      <>
        You can ask us at any time to:
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Access the personal information we hold about you.</li>
          <li>Correct anything that is inaccurate.</li>
          <li>Delete your information (subject to legal record-keeping obligations).</li>
          <li>Stop receiving any optional communications.</li>
        </ul>
        Email{' '}
        <a href="mailto:hello@lumiiadvisory.com" className="text-gold hover:text-near-black underline">
          hello@lumiiadvisory.com
        </a>{' '}
        and we will respond within 30 days. If you are unhappy with our response, you have the right to lodge a
        complaint with the Office of the Australian Information Commissioner (OAIC) at oaic.gov.au.
      </>
    ),
  },
  {
    heading: '8. Cookies',
    body: 'The site uses a small number of cookies — essential cookies for navigation and Google Analytics cookies for anonymous traffic measurement. You can disable cookies in your browser at any time without losing access to the content.',
  },
  {
    heading: '9. Updates to this policy',
    body: 'We may update this policy from time to time. The current version is always available at this URL with a "last updated" date below. Material changes will be flagged on the homepage.',
  },
  {
    heading: '10. Contact',
    body: (
      <>
        Questions about this policy or how we handle your data? Email{' '}
        <a href="mailto:hello@lumiiadvisory.com" className="text-gold hover:text-near-black underline">
          hello@lumiiadvisory.com
        </a>
        .
      </>
    ),
  },
]

export default function PrivacyPolicyPage() {
  return (
    <>
      {/* Hero */}
      <section className="bg-near-black pt-40 pb-20 px-8 lg:px-12">
        <div className="max-w-[860px] mx-auto">
          <p className="font-body text-[11px] tracking-[0.3em] uppercase text-gold mb-6">Legal</p>
          <h1 className="font-display font-light text-[clamp(40px,5vw,68px)] leading-[1.08] text-warm-white mb-6 tracking-[-0.01em]">
            Privacy Policy
          </h1>
          <p className="font-body text-[16px] leading-[1.8] text-warm-white/60 max-w-[640px] font-light">
            How Lumii Advisory collects, uses and protects your information. Plain English. Australian Privacy Act
            compliant.
          </p>
          <p className="font-body text-[12px] tracking-[0.15em] uppercase text-ash mt-8">Last updated: April 2026</p>
        </div>
      </section>

      {/* Body */}
      <section className="bg-warm-white py-[clamp(60px,8vw,100px)] px-8 lg:px-12">
        <div className="max-w-[760px] mx-auto space-y-12">
          {sections.map((s) => (
            <div key={s.heading}>
              <h2 className="font-display font-light text-[clamp(22px,2.4vw,28px)] text-near-black leading-[1.3] mb-4">
                {s.heading}
              </h2>
              <div className="font-body text-[15px] leading-[1.85] text-slate-warm font-light">{s.body}</div>
            </div>
          ))}
          <div className="pt-10 border-t border-parchment">
            <Link
              href="/contact"
              className="font-body text-[12px] tracking-[0.12em] uppercase text-near-black border border-near-black px-8 py-4 hover:bg-near-black hover:text-warm-white transition-all duration-200 inline-block"
            >
              Get in touch →
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}
