import type { Metadata } from 'next'
import LegalPage from '@/components/lumii/LegalPage'
import Link from 'next/link'

export const metadata: Metadata = {
  title: {
    absolute: 'Privacy Policy | Lumii Advisory',
  },
  description:
    'How Lumii Advisory collects, uses and protects your data. Plain-English privacy policy compliant with the Australian Privacy Act.',
  alternates: {
    canonical: 'https://lumiiadvisory.com/privacy-policy',
  },
}

const sections = [
  {
    heading: '1. Who I am',
    body: (
      <>
        Lumii Advisory (&ldquo;Lumii&rdquo;, &ldquo;I&rdquo;, &ldquo;my&rdquo; or &ldquo;me&rdquo;) is a sole-trader
        consulting business operated by Agata Adamczak, based in Sydney, NSW, Australia. This policy explains how I
        handle personal information collected through{' '}
        <Link href="/">
          lumiiadvisory.com
        </Link>{' '}
        and through my advisory engagements. I comply with the Australian Privacy Principles (APPs) under the{' '}
        <em>Privacy Act 1988</em> (Cth).
      </>
    ),
  },
  {
    heading: '2. What I collect',
    body: (
      <>
        I only collect information you provide directly or that is generated by your use of the site:
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Name, email, company and message content when you submit my contact or discovery-call form.</li>
          <li>Email address when you opt in to receive an Insights or resource follow-up.</li>
          <li>
            Anonymous traffic and behaviour data via Google Analytics 4 (page views, referrer, approximate location,
            device type). I do not link this data to identifiable individuals.
          </li>
          <li>Standard server logs (IP, user agent) retained for security and debugging purposes only.</li>
        </ul>
      </>
    ),
  },
  {
    heading: '3. How I use your information',
    body: (
      <>
        I use your information solely to:
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Respond to your enquiry and arrange any discovery call or proposal you request.</li>
          <li>Deliver any resource, checklist, or content you specifically request.</li>
          <li>Improve the website&rsquo;s structure, content and performance.</li>
          <li>Comply with legal and tax record-keeping obligations.</li>
        </ul>
        I do not sell, rent or trade your personal information. I do not use it to train any AI model.
      </>
    ),
  },
  {
    heading: '4. Who I share information with',
    body: (
      <>
        I share personal information only with vetted service providers who act on my behalf and only to the extent
        necessary:
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Google Workspace &amp; Gmail — email correspondence and document storage.</li>
          <li>Netlify — website hosting and form submission delivery.</li>
          <li>Google Analytics 4 — anonymous website analytics.</li>
          <li>Calendly — discovery-call scheduling, where used.</li>
        </ul>
        These providers are bound by their own privacy policies and (where applicable) by data-processing agreements.
        I may also disclose information where required by law.
      </>
    ),
  },
  {
    heading: '5. Where your data is stored',
    body: 'Most of my service providers store data in the United States or Europe under standard contractual clauses or equivalent safeguards. By submitting information to me you consent to your data being processed outside Australia for these purposes.',
  },
  {
    heading: '6. How long I keep it',
    body: 'I retain enquiry and engagement-related records for as long as the relationship is active and for up to seven years afterwards to meet Australian tax and record-keeping obligations. Anonymous analytics data is retained on default Google Analytics 4 settings (currently 14 months).',
  },
  {
    heading: '7. Your rights',
    body: (
      <>
        You can ask me at any time to:
        <ul className="list-disc pl-6 mt-3 space-y-2">
          <li>Access the personal information I hold about you.</li>
          <li>Correct anything that is inaccurate.</li>
          <li>Delete your information (subject to legal record-keeping obligations).</li>
          <li>Stop receiving any optional communications.</li>
        </ul>
        Email{' '}
        <a href="mailto:hello@lumiiadvisory.com">
          hello@lumiiadvisory.com
        </a>{' '}
        and I will respond within 30 days. If you are unhappy with my response, you have the right to lodge a
        complaint with the Office of the Australian Information Commissioner (OAIC) at oaic.gov.au.
      </>
    ),
  },
  {
    heading: '8. Cookies',
    body: 'The site uses a small number of cookies — essential cookies for navigation and Google Analytics cookies for anonymous traffic measurement. You can disable cookies in your browser at any time without losing access to the content.',
  },
  {
    heading: '9. Updates to this policy',
    body: 'I may update this policy from time to time. The current version is always available at this URL with a "last updated" date below. Material changes will be flagged on the homepage.',
  },
  {
    heading: '10. Contact',
    body: (
      <>
        Questions about this policy or how I handle your data? Email{' '}
        <a href="mailto:hello@lumiiadvisory.com">
          hello@lumiiadvisory.com
        </a>
        .
      </>
    ),
  },
]

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy policy"
      lead="How Lumii Advisory collects, uses and protects your information. Plain English. Australian Privacy Act compliant."
      updated="April 2026"
      sections={sections}
    />
  )
}
