export type PricingTier = 'Free' | 'Freemium' | 'Paid'

export interface AiTool {
  name: string
  category: string
  tagline: string
  bestFor: string
  pricing: PricingTier
  website: string
}

export const AI_TOOLS: AiTool[] = [
  // ── Writing & Content ──────────────────────────────────────────────
  {
    name: 'ChatGPT',
    category: 'Writing & Content',
    tagline: "The world's most widely used AI assistant",
    bestFor: 'Drafting emails, brainstorming, summarising documents',
    pricing: 'Freemium',
    website: 'https://chat.openai.com',
  },
  {
    name: 'Claude',
    category: 'Writing & Content',
    tagline: 'Thoughtful AI built for nuanced, long-form work',
    bestFor: 'Long documents, careful reasoning, sensitive topics',
    pricing: 'Freemium',
    website: 'https://claude.ai',
  },
  {
    name: 'Jasper',
    category: 'Writing & Content',
    tagline: 'Marketing copy engine with brand voice control',
    bestFor: 'Ad copy, product descriptions, campaign content',
    pricing: 'Paid',
    website: 'https://www.jasper.ai',
  },
  {
    name: 'Copy.ai',
    category: 'Writing & Content',
    tagline: 'Sales and marketing copy at scale',
    bestFor: 'Cold outreach, landing pages, social captions',
    pricing: 'Freemium',
    website: 'https://www.copy.ai',
  },
  {
    name: 'Writesonic',
    category: 'Writing & Content',
    tagline: 'SEO-aware content generation for web teams',
    bestFor: 'Blog articles, product pages, web copy',
    pricing: 'Freemium',
    website: 'https://writesonic.com',
  },
  {
    name: 'Notion AI',
    category: 'Writing & Content',
    tagline: 'AI writing built directly into your workspace',
    bestFor: 'Meeting notes, project briefs, internal docs',
    pricing: 'Paid',
    website: 'https://www.notion.so/product/ai',
  },

  // ── Research & Search ─────────────────────────────────────────────
  {
    name: 'Perplexity AI',
    category: 'Research & Search',
    tagline: 'AI-powered search with real-time citations',
    bestFor: 'Quick research, fact-checking, sourced answers',
    pricing: 'Freemium',
    website: 'https://www.perplexity.ai',
  },
  {
    name: 'NotebookLM',
    category: 'Research & Search',
    tagline: 'Research assistant grounded in your own documents',
    bestFor: 'Analysing reports, contracts, research papers',
    pricing: 'Free',
    website: 'https://notebooklm.google.com',
  },
  {
    name: 'Elicit',
    category: 'Research & Search',
    tagline: 'Academic literature review powered by AI',
    bestFor: 'Synthesising research papers, evidence analysis',
    pricing: 'Freemium',
    website: 'https://elicit.com',
  },
  {
    name: 'Consensus',
    category: 'Research & Search',
    tagline: 'Evidence-based answers from scientific literature',
    bestFor: 'Health, science, and policy research questions',
    pricing: 'Freemium',
    website: 'https://consensus.app',
  },
  {
    name: 'Gemini Nano',
    category: 'Research & Search',
    tagline: "Google's lightweight on-device AI model",
    bestFor: 'On-device summarisation and smart replies on Android',
    pricing: 'Free',
    website: 'https://deepmind.google/technologies/gemini/nano/',
  },

  // ── Image Generation ──────────────────────────────────────────────
  {
    name: 'Midjourney',
    category: 'Image Generation',
    tagline: 'Industry-leading artistic image generation',
    bestFor: 'Brand visuals, concept art, editorial imagery',
    pricing: 'Paid',
    website: 'https://www.midjourney.com',
  },
  {
    name: 'Adobe Firefly',
    category: 'Image Generation',
    tagline: 'Commercially safe AI imagery inside Adobe tools',
    bestFor: 'Marketing assets, product visuals, safe commercial use',
    pricing: 'Freemium',
    website: 'https://firefly.adobe.com',
  },
  {
    name: 'DALL-E 3',
    category: 'Image Generation',
    tagline: "OpenAI's photorealistic image generator",
    bestFor: 'Illustrations, scenes, and concept visualisation',
    pricing: 'Freemium',
    website: 'https://openai.com/dall-e-3',
  },
  {
    name: 'Ideogram',
    category: 'Image Generation',
    tagline: 'Generates images with accurate readable text',
    bestFor: 'Posters, social graphics, type-heavy visuals',
    pricing: 'Freemium',
    website: 'https://ideogram.ai',
  },
  {
    name: 'Leonardo.ai',
    category: 'Image Generation',
    tagline: 'Fine-tuned models for consistent creative output',
    bestFor: 'Product mockups, game assets, stylised content',
    pricing: 'Freemium',
    website: 'https://leonardo.ai',
  },

  // ── Video Creation ────────────────────────────────────────────────
  {
    name: 'Runway',
    category: 'Video Creation',
    tagline: 'AI video generation and professional editing',
    bestFor: 'Short-form content, creative video, motion graphics',
    pricing: 'Freemium',
    website: 'https://runwayml.com',
  },
  {
    name: 'HeyGen',
    category: 'Video Creation',
    tagline: 'AI avatar videos with multilingual dubbing',
    bestFor: 'Training videos, translated marketing content',
    pricing: 'Freemium',
    website: 'https://www.heygen.com',
  },
  {
    name: 'Synthesia',
    category: 'Video Creation',
    tagline: 'Corporate video production without cameras or studios',
    bestFor: 'L&D content, onboarding, internal communications',
    pricing: 'Paid',
    website: 'https://www.synthesia.io',
  },
  {
    name: 'Sora',
    category: 'Video Creation',
    tagline: "OpenAI's cinematic text-to-video model",
    bestFor: 'High-quality video clips from text prompts',
    pricing: 'Paid',
    website: 'https://sora.com',
  },
  {
    name: 'Kling AI',
    category: 'Video Creation',
    tagline: 'Realistic video generation from images or text',
    bestFor: 'Product animations, scene transitions, social video',
    pricing: 'Freemium',
    website: 'https://klingai.com',
  },
  {
    name: 'Luma Dream Machine',
    category: 'Video Creation',
    tagline: 'Cinematic AI video clips from prompts or stills',
    bestFor: 'Establishing shots, product showcases, b-roll',
    pricing: 'Freemium',
    website: 'https://lumalabs.ai/dream-machine',
  },

  // ── Audio & Voice ─────────────────────────────────────────────────
  {
    name: 'ElevenLabs',
    category: 'Audio & Voice',
    tagline: 'Hyper-realistic AI voice cloning and synthesis',
    bestFor: 'Voiceovers, audiobooks, multilingual narration',
    pricing: 'Freemium',
    website: 'https://elevenlabs.io',
  },
  {
    name: 'Murf',
    category: 'Audio & Voice',
    tagline: 'Studio-quality AI voiceovers for content teams',
    bestFor: 'E-learning, explainer videos, presentations',
    pricing: 'Freemium',
    website: 'https://murf.ai',
  },
  {
    name: 'Descript',
    category: 'Audio & Voice',
    tagline: 'Edit audio and video by editing the transcript',
    bestFor: 'Podcast editing, video post-production, clipping',
    pricing: 'Freemium',
    website: 'https://www.descript.com',
  },
  {
    name: 'Suno',
    category: 'Audio & Voice',
    tagline: 'Generate original music from a text description',
    bestFor: 'Background music, jingles, custom brand audio',
    pricing: 'Freemium',
    website: 'https://suno.com',
  },
  {
    name: 'Udio',
    category: 'Audio & Voice',
    tagline: 'High-fidelity AI music across any genre or style',
    bestFor: 'Soundtrack creation, music prototyping',
    pricing: 'Freemium',
    website: 'https://www.udio.com',
  },

  // ── Presentations & Design ────────────────────────────────────────
  {
    name: 'Gamma',
    category: 'Presentations & Design',
    tagline: 'AI-generated decks, docs, and web pages',
    bestFor: 'Fast decks, proposals, reports with good design',
    pricing: 'Freemium',
    website: 'https://gamma.app',
  },
  {
    name: 'Beautiful.ai',
    category: 'Presentations & Design',
    tagline: 'Slide design that automatically looks polished',
    bestFor: 'Consistent, on-brand presentations at speed',
    pricing: 'Paid',
    website: 'https://www.beautiful.ai',
  },
  {
    name: 'Tome',
    category: 'Presentations & Design',
    tagline: 'Narrative-first AI presentation tool',
    bestFor: 'Storytelling decks, pitch narratives, board updates',
    pricing: 'Freemium',
    website: 'https://tome.app',
  },
  {
    name: 'Canva AI',
    category: 'Presentations & Design',
    tagline: 'Full design suite with deep AI integration',
    bestFor: 'Social content, presentations, brand materials',
    pricing: 'Freemium',
    website: 'https://www.canva.com/ai-image-generator/',
  },

  // ── Coding & Development ──────────────────────────────────────────
  {
    name: 'GitHub Copilot',
    category: 'Coding & Development',
    tagline: 'AI pair programmer inside your existing IDE',
    bestFor: 'Code completion, refactoring, code explanation',
    pricing: 'Paid',
    website: 'https://github.com/features/copilot',
  },
  {
    name: 'Cursor',
    category: 'Coding & Development',
    tagline: 'AI-native code editor built on VS Code',
    bestFor: 'Full codebase understanding, multi-file edits',
    pricing: 'Freemium',
    website: 'https://www.cursor.com',
  },
  {
    name: 'Bolt',
    category: 'Coding & Development',
    tagline: 'Build and deploy full-stack apps from text',
    bestFor: 'Rapid prototyping, MVPs, internal tools',
    pricing: 'Freemium',
    website: 'https://bolt.new',
  },
  {
    name: 'v0',
    category: 'Coding & Development',
    tagline: 'Generate React UI components from descriptions',
    bestFor: 'Front-end scaffolding, design-to-code workflows',
    pricing: 'Freemium',
    website: 'https://v0.dev',
  },
  {
    name: 'Replit AI',
    category: 'Coding & Development',
    tagline: 'Collaborative coding and deployment with AI assist',
    bestFor: 'Learning to code, quick prototypes, team projects',
    pricing: 'Freemium',
    website: 'https://replit.com',
  },
  {
    name: 'Tabnine',
    category: 'Coding & Development',
    tagline: 'Privacy-focused AI code completion',
    bestFor: 'Enterprise teams needing on-prem or private AI',
    pricing: 'Freemium',
    website: 'https://www.tabnine.com',
  },

  // ── Meetings & Productivity ───────────────────────────────────────
  {
    name: 'Otter.ai',
    category: 'Meetings & Productivity',
    tagline: 'Live transcription and AI meeting summaries',
    bestFor: 'Capturing action items, sharing meeting notes',
    pricing: 'Freemium',
    website: 'https://otter.ai',
  },
  {
    name: 'Fireflies.ai',
    category: 'Meetings & Productivity',
    tagline: 'Meeting recorder with AI search across all calls',
    bestFor: 'Sales calls, team stand-ups, client meetings',
    pricing: 'Freemium',
    website: 'https://fireflies.ai',
  },
  {
    name: 'Granola',
    category: 'Meetings & Productivity',
    tagline: 'AI notepad that enhances your own meeting notes',
    bestFor: 'Professionals who take their own notes and want AI enhancement',
    pricing: 'Freemium',
    website: 'https://www.granola.so',
  },
  {
    name: 'Microsoft Copilot',
    category: 'Meetings & Productivity',
    tagline: 'AI across Word, Excel, Teams, Outlook and more',
    bestFor: 'Teams already on Microsoft 365 wanting AI everywhere',
    pricing: 'Freemium',
    website: 'https://www.microsoft.com/en-us/microsoft-copilot',
  },
  {
    name: 'Reclaim AI',
    category: 'Meetings & Productivity',
    tagline: 'AI scheduler that protects time for real work',
    bestFor: 'Focus blocks, habit scheduling, team time coordination',
    pricing: 'Freemium',
    website: 'https://reclaim.ai',
  },

  // ── Data & Analytics ──────────────────────────────────────────────
  {
    name: 'Julius AI',
    category: 'Data & Analytics',
    tagline: 'Chat with your spreadsheets and data files',
    bestFor: 'Data analysis without writing code or formulas',
    pricing: 'Freemium',
    website: 'https://julius.ai',
  },
  {
    name: 'Obviously AI',
    category: 'Data & Analytics',
    tagline: 'No-code predictive machine learning',
    bestFor: 'Churn prediction, sales forecasting, segmentation',
    pricing: 'Paid',
    website: 'https://www.obviously.ai',
  },
  {
    name: 'Polymer',
    category: 'Data & Analytics',
    tagline: 'Turn spreadsheets into interactive dashboards',
    bestFor: 'Non-technical teams exploring data visually',
    pricing: 'Paid',
    website: 'https://www.polymersearch.com',
  },
  {
    name: 'Tableau AI',
    category: 'Data & Analytics',
    tagline: 'AI-powered analytics embedded in Tableau',
    bestFor: 'Enterprise BI teams scaling insight delivery',
    pricing: 'Paid',
    website: 'https://www.tableau.com/solutions/ai',
  },

  // ── SEO & Marketing ───────────────────────────────────────────────
  {
    name: 'Surfer SEO',
    category: 'SEO & Marketing',
    tagline: 'Content optimisation guided by real ranking data',
    bestFor: 'Blog posts and web pages targeting search traffic',
    pricing: 'Paid',
    website: 'https://surferseo.com',
  },
  {
    name: 'Semrush AI',
    category: 'SEO & Marketing',
    tagline: 'All-in-one SEO, PPC, and content marketing platform',
    bestFor: 'Keyword research, competitor analysis, content briefs',
    pricing: 'Paid',
    website: 'https://www.semrush.com',
  },
  {
    name: 'MarketMuse',
    category: 'SEO & Marketing',
    tagline: 'AI content strategy and topical authority planning',
    bestFor: 'Building comprehensive content programmes at scale',
    pricing: 'Paid',
    website: 'https://www.marketmuse.com',
  },
  {
    name: 'AdCreative.ai',
    category: 'SEO & Marketing',
    tagline: 'AI-generated ad creatives for paid campaigns',
    bestFor: 'Facebook, Google, and display ad creative testing',
    pricing: 'Paid',
    website: 'https://www.adcreative.ai',
  },

  // ── Customer Service & CX ─────────────────────────────────────────
  {
    name: 'Intercom',
    category: 'Customer Service & CX',
    tagline: 'AI-first customer communications platform',
    bestFor: 'Support automation, live chat, customer onboarding',
    pricing: 'Paid',
    website: 'https://www.intercom.com',
  },
  {
    name: 'Zendesk AI',
    category: 'Customer Service & CX',
    tagline: 'AI layered across the full support workflow',
    bestFor: 'Ticket routing, agent assist, self-service deflection',
    pricing: 'Paid',
    website: 'https://www.zendesk.com/service/ai/',
  },
  {
    name: 'Drift',
    category: 'Customer Service & CX',
    tagline: 'Conversational AI for B2B sales and marketing',
    bestFor: 'Website lead qualification and pipeline acceleration',
    pricing: 'Paid',
    website: 'https://www.drift.com',
  },

  // ── HR & Recruiting ───────────────────────────────────────────────
  {
    name: 'HireVue',
    category: 'HR & Recruiting',
    tagline: 'AI video interviewing and hiring assessment',
    bestFor: 'High-volume screening, structured interview scoring',
    pricing: 'Paid',
    website: 'https://www.hirevue.com',
  },
  {
    name: 'Textio',
    category: 'HR & Recruiting',
    tagline: 'AI writing for bias-free job descriptions',
    bestFor: 'Recruiting teams improving candidate response rates',
    pricing: 'Paid',
    website: 'https://textio.com',
  },
  {
    name: 'Kira',
    category: 'HR & Recruiting',
    tagline: 'AI contract and document review for legal and HR',
    bestFor: 'Employment contracts, NDAs, due diligence review',
    pricing: 'Paid',
    website: 'https://kirasystems.com',
  },
]

export const CATEGORIES = [
  'Writing & Content',
  'Research & Search',
  'Image Generation',
  'Video Creation',
  'Audio & Voice',
  'Presentations & Design',
  'Coding & Development',
  'Meetings & Productivity',
  'Data & Analytics',
  'SEO & Marketing',
  'Customer Service & CX',
  'HR & Recruiting',
]
