import type { Metadata } from 'next'
import OfferIntro, { CoverCard } from '@/components/lumii/OfferIntro'
import { TextLink } from '@/components/lumii/primitives'
import { FaqSection, JsonLd, SITE_URL } from '@/components/lumii/seo'
import { OFFER_URLS } from '@/lib/offers'

const PAGE_URL = `${SITE_URL}/services/ai-visibility`
const CALENDLY = 'https://calendly.com/agata-lumiiadvisory'

export const metadata: Metadata = {
  title: {
    absolute: 'AI Visibility & Brand Entity Optimisation | Lumii Advisory',
  },
  description:
    'Make your brand appear when buyers research your category in ChatGPT, Claude, Gemini & Perplexity. AI visibility audits, brand entity optimisation & reporting. Sydney & APAC.',
  alternates: { canonical: PAGE_URL },
  openGraph: {
    title: 'AI Visibility & Brand Entity Optimisation | Lumii Advisory',
    description:
      'Make your brand appear when buyers research your category in ChatGPT, Claude, Gemini & Perplexity. AI visibility audits, brand entity optimisation & reporting.',
    url: PAGE_URL,
  },
}

const DEFINITION =
  'AI visibility is how often and how accurately your brand appears in the answers generated by AI systems — ChatGPT, Claude, Gemini, Perplexity, and Google’s AI Overviews — when people research your category, your competitors, or the problem you solve.'

const layers = [
  {
    number: '01',
    name: 'AI Visibility Audit',
    note: 'THE ENTRY POINT',
    body: 'A fast, fixed-scope diagnostic. I test how your brand shows up across ChatGPT, Claude, Gemini, Perplexity, and AI Overviews for the questions your buyers actually ask — then map exactly where you are absent, misrepresented, or beaten by competitors. You get a clear picture of your current AI presence and the specific gaps costing you consideration.',
    deliverables: ['AI presence map', 'Competitor comparison', 'Prioritised gap list'],
  },
  {
    number: '02',
    name: 'Brand Entity Optimisation',
    note: 'THE FOUNDATIONAL WORK',
    body: 'Being visible to AI is not about keywords — it is about being a well-defined entity the models understand and trust. I fix the structured data, entity consistency, and authoritative-source coverage that make your brand unambiguous to AI systems: who you are, what you do, who you serve, and why you are credible. This is the foundational work that compounds.',
    deliverables: ['Entity architecture', 'Structured-data implementation plan', 'Authoritative-source strategy'],
  },
  {
    number: '03',
    name: 'AI Visibility Reporting',
    note: 'THE ONGOING MEASURE',
    body: 'What gets measured improves. I track your share-of-voice across AI answers over time — which questions surface you, which surface competitors, and how your presence shifts as the work lands. Monthly, in plain English, tied to the buying questions that matter.',
    deliverables: ['Monthly AI share-of-voice report', 'Trend tracking', 'Next-action recommendations'],
  },
]

const faqs = [
  {
    q: 'Why doesn’t my brand appear in ChatGPT recommendations?',
    a: 'Usually because your brand is not a clearly-defined entity the model can trust, your category authority is thin, or competitors have stronger structured presence in the sources AI systems draw from. The audit tells you which.',
  },
  {
    q: 'Is AI visibility the same as SEO?',
    a: 'Related but not the same. SEO optimises for ranked links on a results page. AI visibility optimises for being included, quoted, and recommended inside a generated answer — a different mechanism that rewards entity clarity and authoritative-source coverage, not just page rank.',
  },
  {
    q: 'Can you guarantee my brand will appear in AI answers?',
    a: 'No — and be sceptical of anyone who does. AI answers are not a ranked list you can buy into. I improve your presence measurably and track it honestly; I do not sell guarantees.',
  },
  {
    q: 'Which AI platforms do you cover?',
    a: 'ChatGPT, Claude, Gemini, Perplexity, and Google’s AI Overviews — the systems your buyers are actually using to research.',
  },
  {
    q: 'How is AI visibility measured?',
    a: 'Share-of-voice across AI answers for your priority buying questions, tracked over time against your competitors.',
  },
]

// /work-with-us and the Organization offer catalogue reference this node by
// the same @id, so every page resolves to a single Service entity.
const serviceSchema = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  '@id': `${PAGE_URL}#service`,
  name: 'AI Visibility & Brand Entity Optimisation',
  alternateName: ['AI Visibility', 'Generative engine optimisation', 'AI search visibility'],
  description: `${DEFINITION} Lumii Advisory audits current AI presence, fixes brand entity and structured-data foundations, and reports share-of-voice across AI answers over time.`,
  serviceType: 'AI Visibility',
  provider: { '@id': `${SITE_URL}/#organization` },
  areaServed: [
    { '@type': 'City', name: 'Sydney' },
    { '@type': 'Country', name: 'Australia' },
    { '@type': 'Place', name: 'Asia-Pacific' },
  ],
  audience: { '@type': 'BusinessAudience', audienceType: 'Brands and mid-market businesses' },
  url: PAGE_URL,
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'AI Visibility service layers',
    itemListElement: layers.map((l) => ({
      '@type': 'Offer',
      itemOffered: { '@type': 'Service', name: l.name, description: l.body },
    })),
  },
}

export default function AiVisibilityPage() {
  return (
    <div className="lumii">
      <JsonLd data={serviceSchema} />
      <OfferIntro
        trail={[
          { name: 'Work with Lumii', href: '/work-with-us' },
          { name: 'AI visibility', href: '/services/ai-visibility' },
        ]}
        eyebrow="AI VISIBILITY · SYDNEY & APAC"
        title={
          <>
            When your buyers ask AI who to hire, does your <em>name come up?</em>
          </>
        }
        lead="Your customers have already changed how they research. Before they ever reach your website, they are asking ChatGPT, Claude, Gemini, and Perplexity to shortlist their options. If your brand is not in those answers, you are not on the shortlist — and you will never know you were left off."
        primary={{ href: '/contact?interest=ai-visibility', label: 'Talk about AI visibility' }}
        secondary={{ href: '#audit', label: 'Start with the audit' }}
        media={
          <CoverCard
            label="AI VISIBILITY"
            lines={['Find Your', 'Brand’s', <em key="l">Light</em>]}
            footer={['GET FOUND.', 'GET UNDERSTOOD.', 'GET RECOMMENDED.']}
          />
        }
      />

      <section className="section split" aria-labelledby="what-title">
        <h2 id="what-title">What is AI visibility?</h2>
        <div className="prose">
          <p className="lead">{DEFINITION}</p>
          <p>
            AI visibility is the work of making your brand legible, credible, and quotable to the
            systems that now sit between you and your buyers.
          </p>
        </div>
      </section>

      <section className="section courses" id="audit" aria-labelledby="layers-title">
        <div className="section-top">
          <div>
            <p className="eyebrow">HOW I IMPROVE AI VISIBILITY</p>
            <h2 id="layers-title">Three layers of work.</h2>
          </div>
        </div>
        <div className="card-grid three">
          {layers.map((layer) => (
            <article className="content-card" key={layer.number}>
              <p className="eyebrow">
                {layer.number} / {layer.note}
              </p>
              <h3>{layer.name}</h3>
              <p>{layer.body}</p>
              <p className="eyebrow">DELIVERABLES</p>
              <ul className="deliverables">
                {layer.deliverables.map((d) => (
                  <li key={d}>{d}</li>
                ))}
              </ul>
            </article>
          ))}
        </div>
      </section>

      <section className="section method" aria-label="No guarantees">
        <p className="band-quote">
          I don’t sell rankings, and I won’t promise a position in any AI answer — anyone who does is
          guessing. What I do is measurably improve how, how often, and how accurately your brand
          shows up where your buyers are now making decisions.
        </p>
      </section>

      <section className="section split" aria-labelledby="now-title">
        <div>
          <p className="eyebrow">TIMING</p>
          <h2 id="now-title">Why does AI visibility matter now?</h2>
        </div>
        <div className="prose">
          <p>
            This is not a bet on the future. AI is already the researcher and the shortlister for a
            growing share of your buyers.
          </p>
          <p>
            The brands building AI visibility now are compounding an advantage that is very hard to
            reverse later — the same way early SEO advantages became moats.
          </p>
          <p>
            This is stage-appropriate work: build for AI-as-researcher today, and it compounds as AI
            moves toward acting on your buyers’ behalf.
          </p>
          <TextLink href={`${OFFER_URLS.keynotes}#topic-visibility`}>
            Related talk: Find Your Brand’s Light in the Age of AI
          </TextLink>
        </div>
      </section>

      <FaqSection faqs={faqs} title="Questions buyers ask about AI visibility." />

      <section className="page-cta section">
        <div>
          <h2>Find out what AI is saying about you.</h2>
          <p>A 30-minute call to work out whether the audit is worth running for your category — and what it would cover.</p>
        </div>
        <a className="button" href={CALENDLY} target="_blank" rel="noopener noreferrer">
          Book a discovery call <span aria-hidden="true">↗</span>
        </a>
      </section>
    </div>
  )
}
