import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: {
    absolute: 'AI Visibility & Brand Entity Optimisation | Lumii Advisory',
  },
  description:
    'Make your brand appear when buyers research your category in ChatGPT, Claude, Gemini & Perplexity. AI visibility audits, brand entity optimisation & reporting. Sydney & APAC.',
  alternates: {
    canonical: 'https://lumiiadvisory.com/services/ai-visibility',
  },
  openGraph: {
    title: 'AI Visibility & Brand Entity Optimisation | Lumii Advisory',
    description:
      'Make your brand appear when buyers research your category in ChatGPT, Claude, Gemini & Perplexity. AI visibility audits, brand entity optimisation & reporting.',
    url: 'https://lumiiadvisory.com/services/ai-visibility',
  },
}

const SITE_URL = 'https://lumiiadvisory.com'
const PAGE_URL = `${SITE_URL}/services/ai-visibility`
const CALENDLY = 'https://calendly.com/agata-lumiiadvisory'

const layers = [
  {
    number: '01',
    name: 'AI Visibility Audit',
    note: 'The entry point',
    body: 'A fast, fixed-scope diagnostic. I test how your brand shows up across ChatGPT, Claude, Gemini, Perplexity, and AI Overviews for the questions your buyers actually ask — then map exactly where you are absent, misrepresented, or beaten by competitors. You get a clear picture of your current AI presence and the specific gaps costing you consideration.',
    deliverables: ['AI presence map', 'Competitor comparison', 'Prioritised gap list'],
  },
  {
    number: '02',
    name: 'Brand Entity Optimisation',
    note: 'The foundational work',
    body: 'Being visible to AI is not about keywords — it is about being a well-defined entity the models understand and trust. I fix the structured data, entity consistency, and authoritative-source coverage that make your brand unambiguous to AI systems: who you are, what you do, who you serve, and why you are credible. This is the foundational work that compounds.',
    deliverables: [
      'Entity architecture',
      'Structured-data implementation plan',
      'Authoritative-source strategy',
    ],
  },
  {
    number: '03',
    name: 'AI Visibility Reporting',
    note: 'The ongoing measure',
    body: 'What gets measured improves. I track your share-of-voice across AI answers over time — which questions surface you, which surface competitors, and how your presence shifts as the work lands. Monthly, in plain English, tied to the buying questions that matter.',
    deliverables: [
      'Monthly AI share-of-voice report',
      'Trend tracking',
      'Next-action recommendations',
    ],
  },
]

const faqs = [
  {
    q: "Why doesn't my brand appear in ChatGPT recommendations?",
    a: 'Usually because your brand is not a clearly-defined entity the model can trust, your category authority is thin, or competitors have stronger structured presence in the sources AI systems draw from. The audit tells you which.',
  },
  {
    q: 'Is AI visibility the same as SEO?',
    a: 'Related but not the same. SEO optimises for ranked links on a results page. AI visibility optimises for being included, quoted, and recommended inside a generated answer — a different mechanism that rewards entity clarity and authoritative-source coverage, not just page rank.',
  },
  {
    q: 'Can you guarantee my brand will appear in AI answers?',
    a: 'No — and be sceptical of anyone who does. AI answers are not a ranked list you can buy into. I improve your presence measurably and track it honestly; I do not sell guarantees.',
  },
  {
    q: 'Which AI platforms do you cover?',
    a: "ChatGPT, Claude, Gemini, Perplexity, and Google's AI Overviews — the systems your buyers are actually using to research.",
  },
  {
    q: 'How is this measured?',
    a: 'Share-of-voice across AI answers for your priority buying questions, tracked over time against your competitors.',
  },
]

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  '@id': `${PAGE_URL}#faq`,
  mainEntity: faqs.map((f) => ({
    '@type': 'Question',
    name: f.q,
    acceptedAnswer: { '@type': 'Answer', text: f.a },
  })),
}

const serviceSchema = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  // Matches the @id emitted for this discipline on /services so both blocks
  // resolve to a single Service entity rather than two competing ones.
  '@id': `${SITE_URL}/services#ai-visibility`,
  name: 'AI Visibility & Brand Entity Optimisation',
  alternateName: 'AI Visibility',
  description:
    'AI visibility is how often and how accurately your brand appears in the answers generated by AI systems — ChatGPT, Claude, Gemini, Perplexity, and Google’s AI Overviews — when people research your category, your competitors, or the problem you solve. Lumii Advisory audits current AI presence, fixes brand entity and structured-data foundations, and reports share-of-voice across AI answers over time.',
  serviceType: 'AI Visibility',
  provider: { '@id': `${SITE_URL}/#organization` },
  areaServed: [
    { '@type': 'Country', name: 'Australia' },
    { '@type': 'Place', name: 'Asia-Pacific' },
  ],
  audience: { '@type': 'Audience', audienceType: 'Mid-market businesses' },
  category: 'AI Strategy and Digital Transformation Consulting',
  url: PAGE_URL,
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'AI Visibility service layers',
    itemListElement: layers.map((l) => ({
      '@type': 'Offer',
      itemOffered: {
        '@type': 'Service',
        name: l.name,
        description: l.body,
      },
    })),
  },
}

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  '@id': `${PAGE_URL}#breadcrumb`,
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL },
    { '@type': 'ListItem', position: 2, name: 'Services', item: `${SITE_URL}/services` },
    { '@type': 'ListItem', position: 3, name: 'AI Visibility', item: PAGE_URL },
  ],
}

export default function AiVisibilityPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      {/* Hero — dark */}
      <section className="bg-near-black pt-40 pb-28 px-8 lg:px-12">
        <div className="max-w-[1180px] mx-auto">
          {/* Breadcrumb */}
          <nav aria-label="Breadcrumb" className="mb-10">
            <ol className="flex items-center gap-3 list-none p-0 m-0 font-body text-[11px] tracking-[0.15em] uppercase text-warm-white/40">
              <li>
                <Link href="/" className="hover:text-warm-white transition-colors">
                  Home
                </Link>
              </li>
              <li aria-hidden="true">·</li>
              <li>
                <Link href="/services" className="hover:text-warm-white transition-colors">
                  Services
                </Link>
              </li>
              <li aria-hidden="true">·</li>
              <li className="text-gold">AI Visibility</li>
            </ol>
          </nav>

          <p className="font-body text-[11px] tracking-[0.3em] uppercase text-gold mb-8">
            AI Visibility
          </p>
          <h1 className="font-display font-light text-[clamp(40px,4.8vw,74px)] leading-[1.08] text-warm-white mb-10 tracking-[-0.01em] max-w-[960px]">
            When your buyers ask AI who to hire, does your{' '}
            <em className="italic text-gold">name come up?</em>
          </h1>
          <p className="font-body text-[17px] leading-[1.85] text-warm-white/70 max-w-[680px] font-light mb-12">
            Your customers have already changed how they research. Before they ever reach
            your website, they are asking ChatGPT, Claude, Gemini, and Perplexity to
            shortlist their options. If your brand is not in those answers, you are not on
            the shortlist — and you will never know you were left off. AI Visibility is the
            work of making your brand legible, credible, and quotable to the systems that
            now sit between you and your buyers.
          </p>
          <a
            href={CALENDLY}
            target="_blank"
            rel="noopener noreferrer"
            className="font-body text-[12px] tracking-[0.12em] uppercase text-near-black bg-gold px-9 py-4 hover:bg-gold-light hover:-translate-y-px transition-all duration-200 inline-block"
          >
            Book a discovery call
          </a>
        </div>
      </section>

      {/* Definition — the block an AI system should lift verbatim */}
      <section className="bg-warm-white py-[clamp(70px,9vw,120px)] px-8 lg:px-12 border-b border-parchment">
        <div className="max-w-[1180px] mx-auto grid grid-cols-1 lg:grid-cols-[0.8fr_1.2fr] gap-10 lg:gap-20 items-start">
          <h2 className="font-display font-light text-[clamp(30px,3.4vw,46px)] leading-[1.15] text-near-black tracking-[-0.005em]">
            What is <em className="italic text-gold">AI visibility?</em>
          </h2>
          <div>
            <p className="font-body text-[clamp(18px,1.7vw,22px)] leading-[1.7] text-charcoal font-light pl-8 border-l-2 border-gold">
              AI visibility is how often and how accurately your brand appears in the
              answers generated by AI systems — ChatGPT, Claude, Gemini, Perplexity, and
              Google&rsquo;s AI Overviews — when people research your category, your
              competitors, or the problem you solve.
            </p>
          </div>
        </div>
      </section>

      {/* Layer 01 — light, text left, deliverables right */}
      <section className="bg-ivory py-[clamp(70px,9vw,120px)] px-8 lg:px-12">
        <div className="max-w-[1180px] mx-auto grid grid-cols-1 lg:grid-cols-[1.35fr_1fr] gap-12 lg:gap-24">
          <div>
            <div className="flex items-baseline gap-6 mb-6">
              <span className="font-display text-[clamp(40px,4vw,58px)] font-light text-gold/70 leading-none select-none">
                {layers[0].number}
              </span>
              <p className="font-body text-[10px] tracking-[0.25em] uppercase text-ash">
                {layers[0].note}
              </p>
            </div>
            <h2 className="font-display font-light text-[clamp(28px,3vw,40px)] leading-[1.15] text-near-black mb-6 tracking-[-0.005em]">
              {layers[0].name}
            </h2>
            <p className="font-body text-[16px] leading-[1.85] text-slate-warm font-light">
              {layers[0].body}
            </p>
          </div>
          <div className="lg:pt-24">
            <p className="font-body text-[10px] tracking-[0.25em] uppercase text-ash mb-6 flex items-center gap-4">
              <span className="w-6 h-px bg-gold block" />
              Deliverables
            </p>
            <ul className="space-y-4 list-none p-0 m-0">
              {layers[0].deliverables.map((d) => (
                <li
                  key={d}
                  className="font-body text-[15px] text-charcoal font-light leading-[1.7] pb-4 border-b border-parchment"
                >
                  {d}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Layer 02 — dark full-bleed band, reversed */}
      <section className="bg-near-black py-[clamp(70px,9vw,120px)] px-8 lg:px-12">
        <div className="max-w-[1180px] mx-auto grid grid-cols-1 lg:grid-cols-[1fr_1.35fr] gap-12 lg:gap-24">
          <div className="lg:order-last">
            <div className="flex items-baseline gap-6 mb-6">
              <span className="font-display text-[clamp(40px,4vw,58px)] font-light text-gold leading-none select-none">
                {layers[1].number}
              </span>
              <p className="font-body text-[10px] tracking-[0.25em] uppercase text-ash">
                {layers[1].note}
              </p>
            </div>
            <h2 className="font-display font-light text-[clamp(28px,3vw,40px)] leading-[1.15] text-warm-white mb-6 tracking-[-0.005em]">
              {layers[1].name}
            </h2>
            <p className="font-body text-[16px] leading-[1.85] text-warm-white/60 font-light mb-8">
              {layers[1].body}
            </p>
            <p className="font-body text-[15px] leading-[1.85] text-warm-white/60 font-light">
              This is the same discipline that sits inside{' '}
              <Link
                href="/ai-operating-system"
                className="text-gold hover:text-warm-white underline decoration-gold/40 underline-offset-[4px] hover:decoration-warm-white/60 transition-colors"
              >
                the AI Operating System
              </Link>{' '}
              — structure first, tools second.
            </p>
          </div>
          <div className="lg:order-first">
            <p className="font-body text-[10px] tracking-[0.25em] uppercase text-ash mb-6 flex items-center gap-4">
              <span className="w-6 h-px bg-gold block" />
              Deliverables
            </p>
            <ul className="space-y-4 list-none p-0 m-0">
              {layers[1].deliverables.map((d) => (
                <li
                  key={d}
                  className="font-body text-[15px] text-warm-white/80 font-light leading-[1.7] pb-4 border-b border-[rgba(180,175,168,0.18)]"
                >
                  {d}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Layer 03 — light, single column with inline deliverables */}
      <section className="bg-warm-white py-[clamp(70px,9vw,120px)] px-8 lg:px-12">
        <div className="max-w-[820px] mx-auto">
          <div className="flex items-baseline gap-6 mb-6">
            <span className="font-display text-[clamp(40px,4vw,58px)] font-light text-gold/70 leading-none select-none">
              {layers[2].number}
            </span>
            <p className="font-body text-[10px] tracking-[0.25em] uppercase text-ash">
              {layers[2].note}
            </p>
          </div>
          <h2 className="font-display font-light text-[clamp(28px,3vw,40px)] leading-[1.15] text-near-black mb-6 tracking-[-0.005em]">
            {layers[2].name}
          </h2>
          <p className="font-body text-[16px] leading-[1.85] text-slate-warm font-light mb-10">
            {layers[2].body}
          </p>
          <div className="flex flex-wrap gap-x-10 gap-y-4 pt-8 border-t border-parchment">
            {layers[2].deliverables.map((d) => (
              <span key={d} className="font-body text-[14px] text-charcoal font-light">
                {d}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* Honest framing — the position, set apart */}
      <section className="bg-stone py-[clamp(70px,9vw,120px)] px-8 lg:px-12 border-y border-parchment">
        <div className="max-w-[900px] mx-auto text-center">
          <div className="flex justify-center mb-8">
            <span className="w-12 h-px bg-gold block" />
          </div>
          <p className="font-display text-[clamp(24px,2.9vw,36px)] italic font-light text-near-black leading-[1.45]">
            I don&rsquo;t sell rankings, and I won&rsquo;t promise a position in any AI
            answer — anyone who does is guessing. What I do is measurably improve how, how
            often, and how accurately your brand shows up where your buyers are now making
            decisions.
          </p>
        </div>
      </section>

      {/* Why now */}
      <section className="bg-ivory py-[clamp(70px,9vw,120px)] px-8 lg:px-12">
        <div className="max-w-[1180px] mx-auto grid grid-cols-1 lg:grid-cols-[0.85fr_1.15fr] gap-12 lg:gap-24 items-start">
          <div>
            <div className="flex items-center gap-5 mb-6">
              <span className="w-8 h-px bg-gold block" />
              <p className="font-body text-[11px] tracking-[0.3em] uppercase text-ash">
                Timing
              </p>
            </div>
            <h2 className="font-display font-light text-[clamp(28px,3.2vw,44px)] leading-[1.15] text-near-black tracking-[-0.005em]">
              Why does this matter <em className="italic text-gold">now?</em>
            </h2>
          </div>
          <div className="space-y-6 font-body text-[16px] leading-[1.85] text-slate-warm font-light">
            <p>
              This is not a bet on the future. AI is already the researcher and the
              shortlister for a growing share of your buyers.
            </p>
            <p>
              The brands building AI visibility now are compounding an advantage that is
              very hard to reverse later — the same way early SEO advantages became moats.
            </p>
            <p>
              This is stage-appropriate work: build for AI-as-researcher today, and it
              compounds as AI moves toward acting on your buyers&rsquo; behalf.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="bg-warm-white py-[clamp(70px,9vw,120px)] px-8 lg:px-12 border-t border-parchment">
        <div className="max-w-[1180px] mx-auto">
          <h2 className="font-display font-light text-[clamp(30px,3.4vw,46px)] leading-[1.15] text-near-black mb-14 tracking-[-0.005em] max-w-[640px]">
            Questions buyers ask about <em className="italic text-gold">AI visibility.</em>
          </h2>
          <dl className="border-t border-parchment">
            {faqs.map((f) => (
              <div
                key={f.q}
                className="grid grid-cols-1 lg:grid-cols-[1fr_1.3fr] gap-4 lg:gap-16 py-10 border-b border-parchment"
              >
                <dt>
                  <h3 className="font-display font-light text-[clamp(21px,2vw,26px)] leading-[1.3] text-near-black">
                    {f.q}
                  </h3>
                </dt>
                <dd className="font-body text-[15px] leading-[1.85] text-slate-warm font-light m-0">
                  {f.a}
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-near-black py-[clamp(70px,9vw,110px)] px-8 lg:px-12">
        <div className="max-w-[1180px] mx-auto flex flex-col lg:flex-row items-start lg:items-center justify-between gap-10">
          <div>
            <p className="font-body text-[11px] tracking-[0.3em] uppercase text-gold mb-4">
              Start with the audit
            </p>
            <h2 className="font-display font-light text-[clamp(28px,3.2vw,44px)] leading-[1.15] text-warm-white max-w-[560px]">
              Find out what AI is saying about you.
            </h2>
            <p className="font-body text-[15px] leading-[1.8] text-warm-white/55 font-light mt-4 max-w-[520px]">
              A 30-minute call to work out whether the audit is worth running for your
              category — and what it would cover.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-5 items-start sm:items-center flex-shrink-0">
            <a
              href={CALENDLY}
              target="_blank"
              rel="noopener noreferrer"
              className="font-body text-[12px] tracking-[0.12em] uppercase text-near-black bg-gold px-9 py-4 hover:bg-gold-light hover:-translate-y-px transition-all duration-200 inline-block whitespace-nowrap"
            >
              Book a discovery call
            </a>
            <Link
              href="/services"
              className="font-body text-[12px] tracking-[0.12em] uppercase text-warm-white/60 py-4 border-b border-warm-white/20 hover:text-warm-white hover:border-warm-white/60 transition-all duration-200 whitespace-nowrap"
            >
              All services →
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}
